env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  indent: ["error", "tab"]
  no-tabs: 0
  no-multiple-empty-lines: 0
  import/prefer-default-export: "off"
